DROP SEQUENCE IF EXISTS seq_uid CASCADE;
DROP SEQUENCE IF EXISTS seq_comment_id CASCADE;
DROP SEQUENCE IF EXISTS seq_post_id CASCADE;
DROP SEQUENCE IF EXISTS seq_community_id CASCADE;

DROP SCHEMA IF EXISTS USER_DATA CASCADE;
DROP SCHEMA IF EXISTS INFO CASCADE;
DROP SCHEMA IF EXISTS SECURITY CASCADE;
DROP SCHEMA IF EXISTS TEMPORARY CASCADE;
DROP SCHEMA IF EXISTS UTILITIES CASCADE;

